version: '3.8'

services:
  mariadb:
    image: mariadb:10.11.13
    container_name: mariadb
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sbcreviews
      MYSQL_USER: sbcuser
      MYSQL_PASSWORD: sbcuser
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - mariadb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/sbcreviews
      SPRING_DATASOURCE_USERNAME: sbcuser
      SPRING_DATASOURCE_PASSWORD: sbcuser
    ports:
      - "8080:8080"

volumes:
  mariadb_data:
